# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-12 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=120)),
                ('nid', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='staff')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.GenderModel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=15)),
                ('session', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='staff')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.GenderModel')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.GroupModel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=15)),
                ('bangla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('english', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mathematics', models.DecimalField(decimal_places=2, max_digits=5)),
                ('social_science', models.DecimalField(decimal_places=2, max_digits=5)),
                ('religion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('physics', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chemsitry', models.DecimalField(decimal_places=2, max_digits=5)),
                ('higher_math', models.DecimalField(decimal_places=2, max_digits=5)),
                ('biology', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.DepartmentModel')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=120)),
                ('nid', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='staff')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.GenderModel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.SubjectModel')),
            ],
        ),
    ]
